[package]
name = "rrmm-manifest"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rrmm-archive = { path = "../rrmm-archive" }
rrmm-artifacts = { path = "../rrmm-artifacts" }
rrmm-domain = { path = "../rrmm-domain" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
