import path from "node:path";
import type { PakConflictEdge, PakInventory } from "./pak.js";

export interface PakScanFailure {
  archivePath: string;
  error: string;
}

export interface PakScanReportInput {
  root: string;
  inventories: PakInventory[];
  failures: PakScanFailure[];
  edges: PakConflictEdge[];
}

function relative(root: string, target: string): string {
  return path.relative(root, target).replaceAll(path.sep, "/") || path.basename(target);
}

function markdownCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}

export function renderPakScanReport(input: PakScanReportInput): string {
  const archivesInDisabledDirectories = input.inventories
    .map((inventory) => relative(input.root, inventory.archivePath))
    .filter((archive) => archive.split("/").some((part) => /disabled/i.test(part)));
  const modInventories = input.inventories.filter((inventory) => inventory.archiveName !== "RetroRewind-Windows.pak");
  const totalMembers = modInventories.reduce((sum, inventory) => sum + inventory.members.length, 0);

  const lines = [
    "# Phase 0 Local PAK Inventory",
    "",
    "> Generated by the read-only Phase 0 spike. Paths are relative to the game PAK root.",
    "> Overlap is not proof that payloads differ or that either mod is semantically unsafe.",
    "",
    "## Summary",
    "",
    `- PAK archives discovered: ${input.inventories.length + input.failures.length}`,
    `- Readable mod PAKs: ${modInventories.length}`,
    `- Indexed mod members: ${totalMembers}`,
    `- Pairwise overlap edges: ${input.edges.length}`,
    `- Unreadable archives: ${input.failures.length}`,
    `- Archives beneath disabled-looking directories: ${archivesInDisabledDirectories.length}`,
    "",
    "## Priority Inventory",
    "",
    "| Archive | Members | Packages | Patch generation | Priority increment |",
    "| --- | ---: | ---: | ---: | ---: |",
  ];

  for (const inventory of [...modInventories].sort((first, second) =>
    second.priority.patchIncrement - first.priority.patchIncrement
    || relative(input.root, first.archivePath).localeCompare(relative(input.root, second.archivePath)))) {
    lines.push(`| ${markdownCell(relative(input.root, inventory.archivePath))} | ${inventory.members.length} | ${Object.keys(inventory.packages).length} | ${inventory.priority.patchGeneration} | ${inventory.priority.patchIncrement} |`);
  }

  lines.push("", "## Highest Package Overlaps", "", "| First archive | Second archive | Members | Packages |", "| --- | --- | ---: | ---: |");
  for (const edge of input.edges.slice(0, 50)) {
    lines.push(`| ${markdownCell(relative(input.root, edge.first))} | ${markdownCell(relative(input.root, edge.second))} | ${edge.overlappingMembers} | ${edge.overlappingPackages} |`);
  }
  if (input.edges.length === 0) lines.push("| None | None | 0 | 0 |");

  lines.push("", "## Disabled-Looking Directories", "");
  if (archivesInDisabledDirectories.length === 0) lines.push("No PAK was found beneath a disabled-looking directory.");
  else {
    lines.push("These archives must be treated as potentially active until runtime discovery proves otherwise:", "");
    for (const archive of archivesInDisabledDirectories) lines.push(`- \`${archive}\``);
  }

  lines.push("", "## Read Failures", "");
  if (input.failures.length === 0) lines.push("No read failures.");
  else {
    for (const failure of input.failures) {
      lines.push(`- \`${relative(input.root, failure.archivePath)}\`: ${failure.error}`);
    }
  }

  lines.push(
    "",
    "## Interpretation",
    "",
    "- A priority winner suppresses the losing virtual file; it does not merge behavior.",
    "- Package sidecars must be analyzed as one compatibility unit.",
    "- Hash comparison and semantic enrichment are future phases.",
    "- PAKs under `Content/Paks` must not be considered disabled based on a folder name.",
    "",
  );
  return lines.join("\n");
}
