[package]
name = "rrmm-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
rrmm-archive = { path = "../../crates/rrmm-archive" }
rrmm-application = { path = "../../crates/rrmm-application" }
rrmm-artifacts = { path = "../../crates/rrmm-artifacts" }
rrmm-conflicts = { path = "../../crates/rrmm-conflicts" }
rrmm-domain = { path = "../../crates/rrmm-domain" }
rrmm-deploy = { path = "../../crates/rrmm-deploy" }
rrmm-manifest = { path = "../../crates/rrmm-manifest" }
rrmm-pak = { path = "../../crates/rrmm-pak" }
rrmm-recipes = { path = "../../crates/rrmm-recipes" }
rrmm-steam = { path = "../../crates/rrmm-steam" }
rrmm-store = { path = "../../crates/rrmm-store" }
rrmm-ue4ss = { path = "../../crates/rrmm-ue4ss" }
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true

[build-dependencies]
base64.workspace = true
ed25519-dalek.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
